export const testQuestions = {
  sectionsTitle: {
    ru: ['Социальные ситуации', 'Время наедине', 'Рабочие и творческие привычки', 'Общие привычки и предпочтения'],
    az: ['Sosial vəziyyətlər', 'Təklikdə vaxt', 'İş və yaradıcı vərdişlər', 'Ümumi vərdişlər və üstünlüklər'],
  },
  firstSectionQuestions: {
    ru: [
      { id: 1, question: 'Мне нравится быть в центре внимания.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 2, question: 'Я легко завожу новые знакомства.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 3, question: 'Большие вечеринки меня вдохновляют и заряжают энергией.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 4, question: 'Я часто инициирую общение с незнакомыми людьми.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 5, question: 'Я чувствую себя уставшим после длительного общения с большим количеством людей.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
    ],
    az: [
      { id: 1, question: 'Mən diqqət mərkəzində olmağı sevirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 2, question: 'Mən asanlıqla yeni tanışlıqlar qururam.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 3, question: 'Böyük partiyalar məni ruhlandırır və enerji verir.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 4, question: 'Mən tez-tez tanımadığım insanlarla ünsiyyətə başlayıram.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 5, question: 'Çox insanla uzun ünsiyyətdən sonra yorğun oluram.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
    ],
  },
  secondSectionQuestions: {
    ru: [
      { id: 6, question: 'Мне нужно время наедине, чтобы восстановить силы.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 7, question: 'Я предпочитаю проводить выходные дома, а не на шумных мероприятиях.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 8, question: 'Я наслаждаюсь тихим отдыхом в одиночестве.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 9, question: 'Иногда я чувствую себя перегруженным в больших компаниях.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 10, question: 'Мне комфортнее обсуждать свои мысли с одним человеком, чем с группой.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
    ],
    az: [
      { id: 6, question: 'Mənə enerji toplamaq üçün tək vaxt lazımdır.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 7, question: 'Mən həftə sonunu səs-küylü tədbirlərdə yox, evdə keçirməyi üstün tuturam.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 8, question: 'Mən tək olarkən sakit istirahətdən zövq alıram.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 9, question: 'Bəzən böyük şirkətlərdə özümü yüklənmiş hiss edirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 10, question: 'Fikirlərimi qrupla deyil, bir insanla müzakirə etmək daha rahatdır.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
    ],
  },
  thirdSectionQuestions: {
    ru: [
      { id: 11, question: 'Я предпочитаю работать в команде, чем один.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 12, question: 'Я часто проявляю инициативу на работе или в учебе.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 13, question: 'Я люблю делиться своими идеями и получать обратную связь.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 14, question: 'Мне проще концентрироваться и принимать решения наедине.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 15, question: 'Я часто ищу новые впечатления и активности.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
    ],
    az: [
      { id: 11, question: 'Mən tək yox, komandada işləməyi üstün tuturam.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 12, question: 'Mən tez-tez işdə və ya təhsildə təşəbbüs göstərirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 13, question: 'Mən fikirlərimi paylaşmağı və geri bildirim alamağı sevirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 14, question: 'Mənim üçün tək başına diqqət mərkəzləşmək və qərar qəbul etmək daha asandır.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 15, question: 'Mən tez-tez yeni təcrübələr və fəaliyyətlər axtarıram.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
    ],
  },
  fourthSectionQuestions: {
    ru: [
      { id: 16, question: 'Я люблю спонтанные события и приключения.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 17, question: 'Мне важно иметь глубокие личные отношения с несколькими людьми, чем множество поверхностных контактов.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 18, question: 'Я часто говорю больше, чем слушаю.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 19, question: 'Мне нравится планировать своё время заранее, а не полагаться на импровизацию.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
      { id: 20, question: 'Я могу легко адаптироваться и к общению с людьми, и к одиночеству.', answers: [
        { value: 1, label: 'Совсем не согласен' },
        { value: 2, label: 'Скорее не согласен' },
        { value: 3, label: 'Нейтрально' },
        { value: 4, label: 'Скорее согласен' },
        { value: 5, label: 'Полностью согласен' },
      ] },
    ],
    az: [
      { id: 16, question: 'Mən ani hadisələri və macəraları sevirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 17, question: 'Mənim üçün bir neçə insanla dərin münasibətlər qurmaq daha önəmlidir, yüzlərlə səthi əlaqələrdən.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 18, question: 'Mən tez-tez danışmaqla dinləməkdən çox söz deyirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 19, question: 'Mən vaxtımı əvvəlcədən planlaşdırmağı sevirəm, improvisasiyaya etibar etməyi yox.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
      { id: 20, question: 'Mən asanlıqla həm insanlarla ünsiyyətə, həm də təkliyə uyğunlaşa bilirəm.', answers: [
        { value: 1, label: 'Heç razı deyiləm' },
        { value: 2, label: 'Daha çox razı deyiləm' },
        { value: 3, label: 'Neytral' },
        { value: 4, label: 'Daha çox razıyam' },
        { value: 5, label: 'Tamamilə razıyam' },
      ] },
    ],
  },
};
